---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: web-terminal
  namespace: openshift-gitops
spec:
  goTemplate: true
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: placement-hub-openshift
        requeueAfterSeconds: 180
  syncPolicy:
    preserveResourcesOnDeletion: false
  template:
    metadata:
      name: web-terminal-{{.name}}
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
    spec:
      project: default
      destination:
        server: "{{.server}}"
        namespace: redhat-ods-operator
      source:
        repoURL: https://github.com/eformat/rhoai-policy-collection.git
        path: gitops/applications/web-terminal/operator/overlays/fast
        plugin:
          name: argocd-novault-plugin-kustomize
        targetRevision: main
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: web-terminal-chart
  namespace: openshift-gitops
spec:
  goTemplate: true
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: placement-hub-openshift
        requeueAfterSeconds: 180
  syncPolicy:
    preserveResourcesOnDeletion: false
  template:
    metadata:
      name: web-terminal-chart-{{.name}}
      annotations:
        argocd.argoproj.io/compare-options: IgnoreExtraneous
    spec:
      project: default
      destination:
        server: "{{.server}}"
        namespace: redhat-ods-operator
      source:
        repoURL: https://github.com/eformat/rhoai-policy-collection.git
        path: gitops/applications/web-terminal/chart
        plugin:
          name: argocd-novault-plugin-helm
        targetRevision: main
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
